# Generated by Django 3.2.7 on 2021-09-18 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Number', models.IntegerField()),
                ('WhatsappNo', models.IntegerField()),
                ('EmailD', models.CharField(max_length=50)),
                ('Desc', models.TextField()),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
