# Generated by Django 3.2.7 on 2021-09-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueregister',
            name='Number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='catalogueregister',
            name='WhatsappNo',
            field=models.BigIntegerField(),
        ),
    ]
