# Generated by Django 3.2.7 on 2021-09-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210918_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueregister',
            name='Number',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='catalogueregister',
            name='WhatsappNo',
            field=models.CharField(max_length=13),
        ),
    ]
