# Generated by Django 3.2.7 on 2021-09-18 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210918_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docName', models.CharField(max_length=100)),
                ('doc', models.FileField(upload_to='pics')),
                ('Desc', models.TextField()),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
    ]
