# Generated by Django 3.2.7 on 2021-09-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cataloguedocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloguedocuments',
            name='docType',
            field=models.CharField(choices=[('E', 'E-Catalogue'), ('T', 'Tech. Spec.')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
