# Generated by Django 3.2.7 on 2021-09-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cataloguedocuments_doctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueregister',
            name='isSubscribe',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cataloguedocuments',
            name='docType',
            field=models.CharField(choices=[('E', 'E-Catalogue'), ('T', 'Tech. Spec.'), ('C', 'E-Catalogue')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cataloguedocuments',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
